### PR TITLE
Initial plugin

### PR DESCRIPTION
**Pull request by timja**
cc @casz @oleg-nenashev

### CODE REVIEW

**Review by jetersen — APPROVED** [review]
LGTM

**Comment by jetersen** [comment]
Properly be nice to have dependabot once moved to jenkinsci?

**Comment by timja** [comment]
> Properly be nice to have dependabot once moved to jenkinsci?

Shall I start the HOSTING, or wait for Oleg?

**Comment by oleg-nenashev** [comment]
Why do we need a separate lib? If you want it to be accepted to Jenkins, I believe it has to be a plugin then (with a shaded lib inside to avoid conflicts with direct usages)

**Comment by timja** [comment]
https://github.com/jenkinsci/configuration-as-code-plugin/pull/1205#issuecomment-557492533

**Comment by jetersen** [comment]
You should be able to use `mvn deploy` to upload a snapshot to repo.jenkins-ci.org

**Pull request closed without merging**
